#!/bin/bash

# git的alias, 一般都会结合oh-my-zsh安装
# view zsh default theme's git plugin: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git/git.plugin.zsh
alias ga="git add"
alias gst="git status"
alias glog="git log"
alias gb="git branch"
alias gba="git branch -a"
alias gco="git checkout"
alias gd="git diff"
alias gfo="git fetch origin"
alias gr="git pull --rebase"
alias grm="git fetch && git rebase origin/master" # rebase master
alias gp="git push"
alias gcm="git commit -m"
